#!/usr/bin/env python3

import sys
import argparse

from rofication import RoficationGui, RoficationClient

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="View and manage desktop notifications"
    )
    parser.add_argument(
        "-r",
        "--reverse",
        help="display in reverse-chronological order",
        action='store_true',
    )
    parser.add_argument(
        "-t",
        "--timefmt",
        help="output time described by the specified strftime(3) format",
    )
    args = parser.parse_args()

    RoficationGui(
        client=RoficationClient(sys.stdout),
        reverse=args.reverse,
        timefmt=args.timefmt,
    ).run()
